### ISSUE TITLE
The conventional particle filter out performed box filter in the result of simulation in main.m?

### ISSUE THREAD

**Issue by luohc2004** [evbernardes/BoxParticleFilter#1]
Is the result right? Why? I thought box filter can help performance, at least in computation time. 
I run the simulation again, the filter does not diverge.
![图片](https://user-images.githubusercontent.com/6418475/86773035-ac2d7680-c087-11ea-9b37-06d6c5e63b5e.png)

**Comment by evbernardes** [comment]
Hello! Sorry for taking so long to see your comment.
I briefly worked with particle and box particle filters some years ago but I'm by no means an expert.
If I remember correctly, I could demonstrate that the Box Particle Filter could perform at least as good as the conventional filter and was, in some cases, more stable.

I haven't maintained this code here since 2017, so I'd strongly recommend you to look for some other implementation (or use this one as a basis for the creation of another one)

**Comment by luohc2004** [comment]
Thanks for your reply. I will try to find out it myself. And thanks again for your sharing~
